//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACT.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Batch
    {
        public int Id { get; set; }
        public string BatchNo { get; set; }
        public string BatchTable { get; set; }
        public string BatchInNotes { get; set; }
        public string BatchOutNotes { get; set; }
        public System.DateTime RunDate { get; set; }
        public System.DateTime FinishDate { get; set; }
        public string BatchSource { get; set; }
        public Nullable<int> BatchRows { get; set; }
        public string BatchComm { get; set; }
    }
}
