//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACT.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillingInvoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BillingInvoice()
        {
            this.BillingInvoiceLineItems = new HashSet<BillingInvoiceLineItem>();
        }
    
        public int Id { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string PostalCode { get; set; }
        public string Province { get; set; }
        public string Town { get; set; }
        public string AccountNumber { get; set; }
        public string Bank { get; set; }
        public int AccountType { get; set; }
        public string Branch { get; set; }
        public string ContactNumber { get; set; }
        public string ContactEmail { get; set; }
        public string ContactPerson { get; set; }
        public string CompanyName { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<System.DateTime> StatementDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<decimal> InvoiceAmount { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> PSPId { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<int> Status { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<int> InvoiceType { get; set; }
        public Nullable<int> PSPBillingId { get; set; }
        public string PSPName { get; set; }
        public string ClientName { get; set; }
        public string VatNumber { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual PSPBilling PSPBilling { get; set; }
        public virtual PSP PSP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillingInvoiceLineItem> BillingInvoiceLineItems { get; set; }
    }
}
