//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACT.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChepLoadChep
    {
        public int Id { get; set; }
        public int ChepLoadId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public string PCN { get; set; }
        public string PRN { get; set; }
        public string DocketNumber { get; set; }
        public string Reference { get; set; }
        public int Quantity { get; set; }
        public int Status { get; set; }
    
        public virtual ChepLoad ChepLoad { get; set; }
    }
}
