//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACT.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChepAudit
    {
        public int Id { get; set; }
        public int SiteId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public string Equipment { get; set; }
        public Nullable<decimal> ChepStockBalance { get; set; }
        public Nullable<decimal> NotInvoiceIn { get; set; }
        public Nullable<decimal> NotInvoiceOut { get; set; }
        public Nullable<decimal> ReqAdjustment { get; set; }
        public Nullable<decimal> NotMCCIn { get; set; }
        public Nullable<decimal> NotMCCOut { get; set; }
        public Nullable<decimal> SuspendITL { get; set; }
        public Nullable<decimal> SuspendMCC { get; set; }
        public Nullable<decimal> AdjustedInvBalance { get; set; }
        public Nullable<decimal> MccBalance { get; set; }
    
        public virtual Site Site { get; set; }
    }
}
