//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACT.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChepLoad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChepLoad()
        {
            this.ChepClients = new HashSet<ChepClient>();
            this.ChepLoad1 = new HashSet<ChepLoad>();
            this.ChepLoadCheps = new HashSet<ChepLoadChep>();
            this.ChepLoadJournals = new HashSet<ChepLoadJournal>();
            this.Disputes = new HashSet<Dispute>();
            this.Tasks = new HashSet<Task>();
        }
    
        public int Id { get; set; }
        public int ClientId { get; set; }
        public Nullable<int> ClientSiteId { get; set; }
        public Nullable<int> ChepLoadId { get; set; }
        public Nullable<int> OutstandingReasonId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public string ChepStatus { get; set; }
        public string TransactionType { get; set; }
        public string DocketNumber { get; set; }
        public string OriginalDocketNumber { get; set; }
        public string UMI { get; set; }
        public string LocationId { get; set; }
        public string Location { get; set; }
        public string OtherPartyId { get; set; }
        public string OtherParty { get; set; }
        public string OtherPartyCountry { get; set; }
        public string EquipmentCode { get; set; }
        public string Equipment { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Ref { get; set; }
        public string OtherRef { get; set; }
        public string BatchRef { get; set; }
        public Nullable<System.DateTime> ShipmentDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreatedBy { get; set; }
        public string InvoiceNumber { get; set; }
        public string Reason { get; set; }
        public string DataSource { get; set; }
        public Nullable<int> BalanceStatus { get; set; }
        public int Status { get; set; }
        public int PostingType { get; set; }
        public bool IsExchange { get; set; }
        public bool IsPSPPickup { get; set; }
        public bool TransporterLiable { get; set; }
        public bool ManuallyMatchedLoad { get; set; }
        public string ManuallyMatchedUID { get; set; }
        public string CorrectedRef { get; set; }
        public string CorrectedOtherRef { get; set; }
        public bool IsExtra { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChepClient> ChepClients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChepLoad> ChepLoad1 { get; set; }
        public virtual ChepLoad ChepLoad2 { get; set; }
        public virtual Client Client { get; set; }
        public virtual ClientSite ClientSite { get; set; }
        public virtual OutstandingReason OutstandingReason { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChepLoadChep> ChepLoadCheps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChepLoadJournal> ChepLoadJournals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dispute> Disputes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task> Tasks { get; set; }
    }
}
