//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACT.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientAuthorisation
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int ClientLoadId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public string Code { get; set; }
        public string LoadNumber { get; set; }
        public System.DateTime AuthorisationDate { get; set; }
        public int Status { get; set; }
    
        public virtual User User { get; set; }
        public virtual ClientLoad ClientLoad { get; set; }
    }
}
