//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACT.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientProductMonthly
    {
        public int Id { get; set; }
        public int ClientProductId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public int Year { get; set; }
        public int Month { get; set; }
        public Nullable<decimal> OpeningBalance { get; set; }
        public Nullable<decimal> OpeningValue { get; set; }
        public Nullable<decimal> MonthIssues { get; set; }
        public Nullable<decimal> MonthReturns { get; set; }
        public Nullable<decimal> MonthTransferIn { get; set; }
        public Nullable<decimal> MonthTransferOut { get; set; }
        public Nullable<decimal> ClosingBalance { get; set; }
        public Nullable<decimal> ClosingValue { get; set; }
        public Nullable<decimal> NetRevenue { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public Nullable<decimal> GrossRevenue { get; set; }
        public int Status { get; set; }
    
        public virtual ClientProduct ClientProduct { get; set; }
    }
}
