//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACT.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryNoteLine
    {
        public int Id { get; set; }
        public int DeliveryNoteId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public string Product { get; set; }
        public string ProductDescription { get; set; }
        public Nullable<decimal> OrderQuantity { get; set; }
        public Nullable<decimal> Delivered { get; set; }
        public decimal Returned { get; set; }
        public string Equipment { get; set; }
        public int Status { get; set; }
    
        public virtual DeliveryNote DeliveryNote { get; set; }
    }
}
