//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACT.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentCost
    {
        public string ModifiedBy { get; set; }
        public int ProductId { get; set; }
        public decimal Rate { get; set; }
        public int Type { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
    }
}
