//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACT.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int Id { get; set; }
        public int TicketId { get; set; }
        public int SenderUserId { get; set; }
        public Nullable<int> ReceiverUserId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public string Details { get; set; }
        public System.Guid UID { get; set; }
        public bool IsClose { get; set; }
        public bool IsSupport { get; set; }
        public int Status { get; set; }
    
        public virtual Ticket Ticket { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
