//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACT.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSPConfig
    {
        public int Id { get; set; }
        public int PSPId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<decimal> PasswordChange { get; set; }
        public Nullable<int> InvoiceRunDay { get; set; }
        public string SystemEmail { get; set; }
        public string FinancialEmail { get; set; }
        public string WelcomeEmailName { get; set; }
        public string DeclineEmailName { get; set; }
        public string ClientCorrespondenceName { get; set; }
        public string DocumentLocation { get; set; }
        public string BillingFileLocation { get; set; }
        public Nullable<System.DateTime> LastBillingRun { get; set; }
        public string ImportEmail { get; set; }
        public string ReceivingManagerEmail { get; set; }
        public string OpsManagerEmail { get; set; }
        public string AdminManagerEmail { get; set; }
        public Nullable<decimal> TaxPercentage { get; set; }
        public string ImportEmailHost { get; set; }
        public string ImportEmailUsername { get; set; }
        public string ImportEmailPassword { get; set; }
        public Nullable<int> ImportEmailPort { get; set; }
        public Nullable<bool> ImportUseSSL { get; set; }
        public Nullable<System.TimeSpan> CollectionRunTime { get; set; }
    
        public virtual PSP PSP { get; set; }
    }
}
