//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACT.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSPClient
    {
        public int Id { get; set; }
        public int PSPId { get; set; }
        public int ClientId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public int Status { get; set; }
        public string FinAccountingCode { get; set; }
        public Nullable<System.DateTime> ContractRenewalDate { get; set; }
    
        public virtual PSP PSP { get; set; }
        public virtual Client Client { get; set; }
    }
}
