//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACT.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSPPeriod
    {
        public int Id { get; set; }
        public int PSPId { get; set; }
        public string Period1 { get; set; }
        public Nullable<System.DateTime> Period1From { get; set; }
        public Nullable<System.DateTime> Period1To { get; set; }
        public string Period2 { get; set; }
        public Nullable<System.DateTime> Period2From { get; set; }
        public Nullable<System.DateTime> Period2To { get; set; }
        public string Period3 { get; set; }
        public Nullable<System.DateTime> Period3From { get; set; }
        public Nullable<System.DateTime> Period3To { get; set; }
        public string Period4 { get; set; }
        public Nullable<System.DateTime> Period4From { get; set; }
        public Nullable<System.DateTime> Period4To1 { get; set; }
        public string Period5 { get; set; }
        public Nullable<System.DateTime> Period5From { get; set; }
        public Nullable<System.DateTime> Period5To { get; set; }
        public string Period6 { get; set; }
        public Nullable<System.DateTime> Period6From { get; set; }
        public Nullable<System.DateTime> Period6To { get; set; }
        public string Period7 { get; set; }
        public Nullable<System.DateTime> Period7From { get; set; }
        public Nullable<System.DateTime> Period7To { get; set; }
        public string Period8 { get; set; }
        public Nullable<System.DateTime> Period8From { get; set; }
        public Nullable<System.DateTime> Period8To { get; set; }
        public string Period9 { get; set; }
        public Nullable<System.DateTime> Period9From { get; set; }
        public Nullable<System.DateTime> Period9To { get; set; }
        public string Period10 { get; set; }
        public Nullable<System.DateTime> Period10From { get; set; }
        public Nullable<System.DateTime> Period10To { get; set; }
        public string Period11 { get; set; }
        public Nullable<System.DateTime> Period11From { get; set; }
        public Nullable<System.DateTime> Period11To { get; set; }
        public string Period12 { get; set; }
        public Nullable<System.DateTime> Period12From { get; set; }
        public Nullable<System.DateTime> Period12To { get; set; }
        public string Period13 { get; set; }
        public Nullable<System.DateTime> Period13From { get; set; }
        public Nullable<System.DateTime> Period13To { get; set; }
    }
}
