//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACT.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteAudit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SiteAudit()
        {
            this.Journals = new HashSet<Journal>();
        }
    
        public int Id { get; set; }
        public int SiteId { get; set; }
        public int ClientId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> AuditDate { get; set; }
        public string Equipment { get; set; }
        public Nullable<decimal> PalletsOutstanding { get; set; }
        public Nullable<decimal> PalletsCounted { get; set; }
        public Nullable<decimal> WriteoffPallets { get; set; }
        public string CustomerName { get; set; }
        public byte[] CustomerSignature { get; set; }
        public string RepName { get; set; }
        public byte[] RepSignature { get; set; }
        public string PalletAuditor { get; set; }
        public byte[] PalletAuditorSign { get; set; }
        public string DocumentLocation { get; set; }
        public int Status { get; set; }
        public Nullable<int> CustomerSignatureId { get; set; }
        public Nullable<int> RepSignatureId { get; set; }
        public Nullable<int> PalletAuditorSignatureId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Journal> Journals { get; set; }
        public virtual Site Site { get; set; }
        public virtual Client Client { get; set; }
    }
}
