//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACT.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteBilling
    {
        public int Id { get; set; }
        public int SiteId { get; set; }
        public int ProductId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> BillingDate { get; set; }
        public Nullable<int> BillingPeriod { get; set; }
        public Nullable<decimal> ProductQuantity { get; set; }
        public Nullable<decimal> ProductAmount { get; set; }
        public string PastelCode { get; set; }
        public int Status { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Site Site { get; set; }
    }
}
