//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACT.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transporter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transporter()
        {
            this.ClientLoads = new HashSet<ClientLoad>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ClientId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public string Name { get; set; }
        public string ContactNumber { get; set; }
        public string Email { get; set; }
        public string TradingName { get; set; }
        public string RegistrationNumber { get; set; }
        public string ContactName { get; set; }
        public string SupplierCode { get; set; }
        public string ClientTransporterCode { get; set; }
        public string ChepClientTransporterCode { get; set; }
        public int Status { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string AddressLine3 { get; set; }
        public string Region { get; set; }
        public string District { get; set; }
        public string Country { get; set; }
        public string EmailAddress2 { get; set; }
        public bool IsAdminClerk { get; set; }
        public bool IsManagement { get; set; }
        public bool ReceiveEmailsAutomatically { get; set; }
        public bool IsActive { get; set; }
        public string Transporter_AddressLine1 { get; set; }
        public string Transporter_AddressLine2 { get; set; }
        public string Transporter_AddressLine3 { get; set; }
        public string Transporter_Region { get; set; }
        public string Transporter_District { get; set; }
        public string Transporter_Country { get; set; }
        public string Transporter_EmailAddress2 { get; set; }
        public bool Transporter_IsAdminClerk { get; set; }
        public bool Transporter_IsManagement { get; set; }
        public bool Transporter_ReceiveEmailsAutomatically { get; set; }
        public bool Transporter_IsActive { get; set; }
    
        public virtual Client Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientLoad> ClientLoads { get; set; }
    }
}
